#!/usr/bin/env python3
"""
run.py — agents-maker PR Review Action runner.

Fetches the PR diff, assembles a reviewer_agent prompt,
calls Claude, and posts a structured refinement_report as a PR comment.
"""

import json
import os
import sys
import urllib.request
import urllib.error
from pathlib import Path

# ---------------------------------------------------------------------------
# Environment
# ---------------------------------------------------------------------------

ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")
GITHUB_TOKEN      = os.environ.get("GITHUB_TOKEN", "")
GITHUB_REPOSITORY = os.environ.get("GITHUB_REPOSITORY", "")
GITHUB_EVENT_PATH = os.environ.get("GITHUB_EVENT_PATH", "")
GITHUB_ACTION_PATH = Path(os.environ.get("GITHUB_ACTION_PATH", str(Path(__file__).parent)))
GITHUB_WORKSPACE  = Path(os.environ.get("GITHUB_WORKSPACE", "."))

MODEL            = os.environ.get("INPUT_MODEL", "claude-haiku-4-5-20251001")
MAX_FILES        = int(os.environ.get("INPUT_MAX_FILES", "20"))
FAIL_ON_CRITICAL = os.environ.get("INPUT_FAIL_ON_CRITICAL", "true").lower() == "true"
INPUT_PR_NUMBER  = os.environ.get("INPUT_PR_NUMBER", "")

DIFF_LINE_LIMIT  = 2000   # truncate very large diffs
DIFF_CHAR_LIMIT  = 12000  # hard cap on chars sent to Claude


# ---------------------------------------------------------------------------
# GitHub API helpers (pure urllib — no extra dependencies)
# ---------------------------------------------------------------------------

def _gh_request(
    url: str,
    method: str = "GET",
    data: dict | None = None,
    accept: str = "application/vnd.github+json",
) -> tuple[int, bytes]:
    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": accept,
        "X-GitHub-Api-Version": "2022-11-28",
        "User-Agent": "agents-maker-review-action/1.0",
    }
    body = json.dumps(data).encode() if data else None
    if body:
        headers["Content-Type"] = "application/json"
    req = urllib.request.Request(url, headers=headers, method=method, data=body)
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return resp.status, resp.read()
    except urllib.error.HTTPError as e:
        return e.code, e.read()


def get_pr_number() -> int:
    if INPUT_PR_NUMBER:
        return int(INPUT_PR_NUMBER)
    if GITHUB_EVENT_PATH and Path(GITHUB_EVENT_PATH).exists():
        event = json.loads(Path(GITHUB_EVENT_PATH).read_text(encoding="utf-8"))
        n = event.get("pull_request", {}).get("number")
        if n:
            return int(n)
    print(
        "[ERROR] Could not determine PR number. "
        "Set INPUT_PR_NUMBER or trigger on pull_request event.",
        file=sys.stderr,
    )
    sys.exit(1)


def get_pr_info(pr_number: int) -> dict:
    url = f"https://api.github.com/repos/{GITHUB_REPOSITORY}/pulls/{pr_number}"
    status, body = _gh_request(url)
    if status != 200:
        return {"title": f"PR #{pr_number}", "body": ""}
    return json.loads(body)


def get_changed_files(pr_number: int) -> list[str]:
    url = f"https://api.github.com/repos/{GITHUB_REPOSITORY}/pulls/{pr_number}/files"
    status, body = _gh_request(url)
    if status != 200:
        return []
    return [f["filename"] for f in json.loads(body)[:MAX_FILES]]


def get_pr_diff(pr_number: int) -> str:
    url = f"https://api.github.com/repos/{GITHUB_REPOSITORY}/pulls/{pr_number}"
    status, body = _gh_request(url, accept="application/vnd.github.v3.diff")
    if status != 200:
        print(f"[ERROR] Failed to fetch PR diff: HTTP {status}", file=sys.stderr)
        sys.exit(1)
    diff = body.decode("utf-8", errors="replace")
    lines = diff.splitlines()
    if len(lines) > DIFF_LINE_LIMIT:
        lines = lines[:DIFF_LINE_LIMIT]
        lines.append(f"... [diff truncated at {DIFF_LINE_LIMIT} lines] ...")
    diff = "\n".join(lines)
    if len(diff) > DIFF_CHAR_LIMIT:
        diff = diff[:DIFF_CHAR_LIMIT] + f"\n... [diff truncated at {DIFF_CHAR_LIMIT} chars] ..."
    return diff


def post_comment(pr_number: int, body: str) -> None:
    url = f"https://api.github.com/repos/{GITHUB_REPOSITORY}/issues/{pr_number}/comments"
    footer = (
        "\n\n---\n"
        "*Generated by [agents-maker](https://github.com/Prateek-N/Multi-Agent-Stack) "
        "· reviewer\\_agent · "
        "[Add to your repo](https://github.com/Prateek-N/Multi-Agent-Stack"
        "/tree/main/actions/review-pr)*"
    )
    status, resp_body = _gh_request(url, method="POST", data={"body": body + footer})
    if status not in (200, 201):
        print(
            f"[WARN] Failed to post comment: HTTP {status} — {resp_body[:300]}",
            file=sys.stderr,
        )
    else:
        comment = json.loads(resp_body)
        print(f"Review comment posted: {comment.get('html_url', '(no URL)')}")


# ---------------------------------------------------------------------------
# Reviewer agent spec loader
# ---------------------------------------------------------------------------

def load_reviewer_spec() -> str:
    candidates = [
        GITHUB_WORKSPACE / "agents-maker" / "agents" / "reviewer_agent.md",
        GITHUB_WORKSPACE / "agents" / "reviewer_agent.md",
        GITHUB_ACTION_PATH.parent.parent.parent / "agents" / "reviewer_agent.md",
    ]
    for path in candidates:
        if path.exists():
            print(f"Loaded reviewer spec from: {path}")
            return path.read_text(encoding="utf-8")

    # Minimal inline fallback — always produces a valid refinement_report
    return """\
# Reviewer Agent
## Role
You are the Reviewer Agent. Review the PR diff for: correctness, security vulnerabilities,
edge cases, missing error handling, performance issues, and code quality.

## Output Contract
Respond ONLY with a refinement_report in this exact format:

## Refinement Report

**Verdict**: ready_to_ship | minor_revisions_needed | significant_revisions_needed

**Summary**: N critical, N high, N medium, N low

### Findings

| Severity | Area | Issue | Recommendation |
|---|---|---|---|

### Positive Findings
- <at least 2 things done well>

### Conformance Check
- Security pass: complete
- Edge cases checked: yes
"""


# ---------------------------------------------------------------------------
# Prompt assembly
# ---------------------------------------------------------------------------

def build_prompt(pr_info: dict, diff: str, files: list[str], reviewer_spec: str) -> str:
    title = pr_info.get("title", "")
    body  = (pr_info.get("body") or "")[:800]
    files_str = "\n".join(f"- {f}" for f in files) if files else "(not available)"
    return (
        f"{reviewer_spec}\n\n"
        f"---\n\n"
        f"## Task\n"
        f"Review this pull request: **{title}**\n\n"
        f"## PR Description\n"
        f"{body if body else '(no description provided)'}\n\n"
        f"## Changed Files ({len(files)} files shown)\n"
        f"{files_str}\n\n"
        f"## Domain\n"
        f"software\n\n"
        f"## Review Focus\n"
        f"correctness, security, edge cases, error handling, code quality\n\n"
        f"## Work Product (PR Diff)\n"
        f"```diff\n{diff}\n```\n"
    )


# ---------------------------------------------------------------------------
# Claude API call
# ---------------------------------------------------------------------------

def call_claude(prompt: str) -> str:
    try:
        import anthropic
    except ImportError:
        print(
            "[ERROR] anthropic package not installed. The action setup step should have "
            "installed it. Check your workflow logs.",
            file=sys.stderr,
        )
        sys.exit(1)

    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)
    response = client.messages.create(
        model=MODEL,
        max_tokens=4096,
        system=(
            "You are the agents-maker Reviewer Agent. "
            "Produce a structured refinement_report. "
            "Be specific: reference actual lines and symbols from the diff. "
            "Never hallucinate file names or function names not in the diff."
        ),
        messages=[{"role": "user", "content": prompt}],
    )
    return response.content[0].text


# ---------------------------------------------------------------------------
# Critical finding detection
# ---------------------------------------------------------------------------

def has_critical(review_text: str) -> bool:
    lower = review_text.lower()
    # Match table rows like "| critical |" or inline mentions
    return "| critical |" in lower or "**critical**" in lower


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    # Validate required env vars
    missing = [v for v in ["ANTHROPIC_API_KEY", "GITHUB_TOKEN", "GITHUB_REPOSITORY"] if not os.environ.get(v)]
    if missing:
        for v in missing:
            print(f"[ERROR] Required environment variable not set: {v}", file=sys.stderr)
        sys.exit(1)

    pr_number = get_pr_number()
    print(f"Reviewing PR #{pr_number} in {GITHUB_REPOSITORY} with model {MODEL}...")

    pr_info = get_pr_info(pr_number)
    files   = get_changed_files(pr_number)
    diff    = get_pr_diff(pr_number)
    spec    = load_reviewer_spec()

    print(f"  Files changed : {len(files)}")
    print(f"  Diff length   : {len(diff.splitlines())} lines / {len(diff)} chars")

    prompt = build_prompt(pr_info, diff, files, spec)
    print("Calling Claude API...")
    review = call_claude(prompt)

    post_comment(pr_number, review)

    if has_critical(review) and FAIL_ON_CRITICAL:
        print("[FAIL] Critical findings found — check the PR comment for details.", file=sys.stderr)
        sys.exit(1)

    if has_critical(review):
        print("[WARN] Critical findings present but FAIL_ON_CRITICAL=false — not failing CI.")
    else:
        print("Review complete — no critical findings.")


if __name__ == "__main__":
    main()
